[tool.ruff]
# See https://beta.ruff.rs/docs/rules/ for details
select = [
    "F",   # Pyflakes, included in default
    "E",
    "W",   # pycodestyles errors and warnings
    "I",   # sorting
    "ANN", # force annotations
    "C",
    "C4",
    "EM",
    "COM",
    "ISC", # flake8 rules
    "ICN",
    "G",
    "INP",
    "Q",
    "PIE",
    "PYI",
    "T20",
    "BLE",
    "ARG",
    "TID",
    "SLF",
    "N",
    "RET",
    "RSE",
    "ERA",
    "PL",  # pylint
]
ignore = ["ANN401", "ANN001", "G004", "ANN002", "INP001", "N818"]
unfixable = []
extend-exclude = [
    ".nox",
    ".pytest_cache",
    ".ruff_cache",
    "test-results",
    ".venv",
    "build",
    "dist",
    "temp",
    ".coverage",
    "noxfile.py",
]

line-length = 120

# Assume Python 3.11.
target-version = "py311"
[tool.ruff.per-file-ignores]
"**/tests/*" = [
    "ARG001",
    "ARG004",
    "INP001",
] # produces a lot of false positives due to usage of fixtures in tests
